package dev.pro.demo.dto;

/**
 * Auto Generated By Generator
 **/

public class Demo {

    private Long id;

    private String userName;

    private String password;

    private String isEnable;

    private String deptCode;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getIsEnable() {
        return isEnable;
    }

    public void setIsEnable(String isEnable) {
        this.isEnable = isEnable;
    }

    public String getDeptCode() {
        return deptCode;
    }

    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode;
    }

    @Override
    public String toString() {
        return "Demo{" +
                "  id=" + id +
                ", userName='" + userName + '\'' +
                ", password='" + password + '\'' +
                ", deptCode='" + deptCode + '\'' +
                "} ";
    }
}
